version: "3"

services:
  
  topsis-web-app-postgres:
    build:
      dockerfile: "Dockerfile"
    ports:
      - "8432:80"
    depends_on:
      - topsis-postgres
    networks:
      - backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  topsis-postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /db/postgres
    volumes:
       - ./Docker/db/postgres:/db/postgres
    logging:
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped


networks:       
  backend:
    driver: bridge